language: elixir
elixir:
- 1.2.6
- 1.3.4
- 1.4.5
- 1.5.2
- 1.6.1
otp_release:
- 18.3
- 19.3
- 20.1
matrix:
  exclude:
  - elixir: 1.2.6
    otp_release: 20.1
  - elixir: 1.3.4
    otp_release: 20.1
  - elixir: 1.6.1
    otp_release: 18.3
  - elixir: 1.6.1
    otp_release: 19.3
env:
- MIX_ENV=test COVERALLS_ELIXIR_VERSION=1.6.1 COVERALLS_OTP_RELEASE=20.1
script:
- mix test

