version: 0.0
os: linux 
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: owner
  AfterInstall:
    - location: scripts/clean.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: owner
