version: 0.0
os: linux 
hooks:
  ApplicationStop:
    - location: script/dregister_from_elb.sh
      runas: owner
    - location: script/stop.sh
      runas: owner
  AfterInstall:
    - location: script/clean.sh
      runas: owner
  ApplicationStart:
    - location: script/register_with_elb.sh
      runas: owner
    - location: script/start.sh
      runas: owner
