version: 0.1

phases:
  build:
    commands:
      - git rev-parse --abbrev-ref HEAD
      - mix deps.get
      - mix local.hex --force
      - mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force
      - mix local.rebar --force
      - mix test
