version: 0.1

phases:
  build:
    commands:
      - git rev-parse --abbrev-ref HEAD
      - mix local.hex --force
      - mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force
      - mix local.rebar --force
      - mix deps.get
      - mix test
      - MIX_ENV=prod mix release
  post_build:
    commands:
      - echo Build completed on `date`
      - cp ./_build/prod/rel/test/releases/*/test.tar.gz .
      - mv test{,$(git describe --tags 2>> /dev/null || git rev-parse HEAD)}.tar.gz 
artifacts:
  files: test*.tar.gz
  discard-paths: yes
