version: 0.1

phases:
  build:
    commands:
      - git rev-parse --abbrev-ref HEAD
      - mix local.hex --force
      - mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force
      - mix local.rebar --force
      - echo Build started on `date` in dir `pwd`
      - mix deps.get
      - mix test
      - MIX_ENV=prod mix release
  post_build:
    commands:
      - echo Build completed on `date`
      - cp ./_build/prod/rel/test/releases/*/test.tar.gz .
      - gunzip test.tar.gz
      - tar -rf test.tar appspec.yml script
      - gzip test.tar
      - bash -c 'mv test{,-$(git describe --tags || git rev-parse HEAD)}.tar.gz'
artifacts:
  files:
    - meta.json
    - test*.tar.gz
  discard-paths: yes
