version: 0.1

phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - git rev-parse --abbrev-ref HEAD
      - mix local.hex --force
      - mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force
      - mix local.rebar --force
      - echo Build started on `date` in dir `pwd`
      - mix deps.get
      - mix test
      - mix release --env=prod
  post_build:
    commands:
      - echo Build completed on `date`
      - cp ./_build/prod/rel/test/releases/*/test.tar.gz .
      - bash -c 'mv test{,-$(git describe --tags 2>> /dev/null || git rev-parse HEAD)}.tar.gz'
      - echo ls test*.tar.gz
artifacts:
  files: 
    - test*.tar.gz
  discard-paths: yes
 
